export const REQUEST_POST_DATA = 'REQUEST_POST_DATA';
export const RECEIVE_POST_DATA = 'RECEIVE_POST_DATA';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const REQUEST_NEW_POST = "REQUEST_NEW_POST";
export const RECEIVE_NEW_POST = "RECEIVE_NEW_POST";


export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export const NEW_POST_FAILED = 'NEW_POST_FAILED';